server.port=8081
spring.application.name=core-service

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=eventdriven_2
spring.datasource.username=psharma51
spring.datasource.password=password

# HikariCP
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

# Flyway
spring.flyway.enabled=true
spring.flyway.schemas=eventdriven_2
spring.flyway.locations=classpath:db/migration

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=eventdriven
